### PR TITLE
Add storage tag to beegfs and nfs clusters

### PR DESCRIPTION
**Pull request by hollysilk**

### CODE REVIEW

**Comment by oneswig** [comment]
I think we might need to do this PR against the `awx` branch, not the `master` branch.  It's picked up quite a lot of other changes besides.

**Comment by brtkwr** [comment]
is this PR/branch still relevant? please close if not

**Comment by priteau** [comment]
I think there's only one relevant commit, which looks good: https://github.com/cedadev/jasmin-appliances/pull/12/commits/f1222f89dcb60fd7d282e85af8cf0ecb23efd446

**Comment by hollysilk** [comment]
Pierre is correct, it's just that one commit. This addresses issue #31 in the project folder. There's also a corresponding PR for jasmin-cluster-infra.

**Comment by brtkwr** [comment]
Ive changed the base to awx-dev... looking a lot more manageable now :)

**Review by priteau — APPROVED** [review]

**Review by oneswig — APPROVED** [review]
This looks good to me, and provided `openstack stack list --tags storage` works when a cluster is deployed in this way, then we are good to go.

In future we might consolidate the storage tags to one parameter, but let's not iterate here.

**Pull request merged**
